# Generated by Django 3.1 on 2021-07-28 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(related_name='Goods', to='sale.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='جزییات کالا'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000000, verbose_name='قیمت کالا'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='درصد رضایت از کالا'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 7, 28, 13, 25, 40, 156110, tzinfo=utc)),
        ),
    ]
