# Generated by Django 3.1 on 2021-07-28 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20210728_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 7, 28, 14, 39, 45, 796864, tzinfo=utc)),
        ),
    ]
