# Generated by Django 3.0.5 on 2020-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display', models.BooleanField(default=True, verbose_name='should be diplayed?')),
                ('position', models.IntegerField(verbose_name='position')),
            ],
            options={
                'verbose_name': 'Categorie',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'new'},
        ),
    ]
