# Generated by Django 3.0.5 on 2020-05-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20200525_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='football.Category', verbose_name='Category'),
        ),
    ]
