# Generated by Django 3.0.5 on 2020-05-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published'], 'verbose_name': 'new'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='No Category', max_length=2000),
        ),
    ]
