# Generated by Django 3.0.5 on 2020-05-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='path',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
